var searchData=
[
  ['interactive_20face_20detection_20c_2b_2b_20demo',['Interactive Face Detection C++ Demo',['../_demos_interactive_face_detection_demo_README.html',1,'']]],
  ['interactive_20face_20recognition_20demo',['Interactive Face Recognition Demo',['../_demos_python_demos_face_recognition_demo_README.html',1,'']]],
  ['image_20retrieval_20python_2a_20demo',['Image Retrieval Python* Demo',['../_demos_python_demos_image_retrieval_demo_README.html',1,'']]],
  ['instance_20segmentation_20python_2a_20demo',['Instance Segmentation Python* Demo',['../_demos_python_demos_instance_segmentation_demo_README.html',1,'']]],
  ['image_20segmentation_20python_2a_20demo',['Image Segmentation Python* Demo',['../_demos_python_demos_segmentation_demo_README.html',1,'']]],
  ['inference_20engine_20demos',['Inference Engine Demos',['../_demos_README.html',1,'']]],
  ['image_20segmentation_20c_2b_2b_20demo',['Image Segmentation C++ Demo',['../_demos_segmentation_demo_README.html',1,'']]],
  ['inference_20engine_20api_20changes_20history',['Inference Engine API Changes History',['../_docs_IE_DG_API_Changes.html',1,'']]],
  ['inference_20engine_20developer_20guide',['Inference Engine Developer Guide',['../_docs_IE_DG_Deep_Learning_Inference_Engine_DevGuide.html',1,'']]],
  ['introduction_20to_20inference_20engine',['Introduction to Inference Engine',['../_docs_IE_DG_inference_engine_intro.html',1,'']]],
  ['introduction_20to_20inference_20engine_20device_20query_20api',['Introduction to Inference Engine Device Query API',['../_docs_IE_DG_InferenceEngine_QueryAPI.html',1,'']]],
  ['integrate_20the_20inference_20engine_20with_20your_20application',['Integrate the Inference Engine with Your Application',['../_docs_IE_DG_Integrate_with_customer_application_new_API.html',1,'']]],
  ['inference_20engine_20kernels_20extensibility',['Inference Engine Kernels Extensibility',['../_docs_IE_DG_Integrate_your_kernels_into_IE.html',1,'']]],
  ['introduction_20to_20the_20performance_20topics',['Introduction to the Performance Topics',['../_docs_IE_DG_Intro_to_Performance.html',1,'']]],
  ['introduction_20to_20intel®_20deep_20learning_20deployment_20toolkit',['Introduction to Intel® Deep Learning Deployment Toolkit',['../_docs_IE_DG_Introduction.html',1,'']]],
  ['inference_20engine_20memory_20primitives',['Inference Engine Memory primitives',['../_docs_IE_DG_Memory_primitives.html',1,'']]],
  ['introduction_20to_20the_20inference_20engine_20neural_20network_20builder',['Introduction to the Inference Engine Neural Network Builder',['../_docs_IE_DG_NNBuilder.html',1,'']]],
  ['inference_20engine_20samples',['Inference Engine Samples',['../_docs_IE_DG_Samples_Overview.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20linux_2a_20using_20apt_20repository',['Install Intel® Distribution of OpenVINO™ toolkit for Linux* Using APT Repository',['../_docs_install_guides_installing_openvino_apt.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20linux_2a_20from_20a_20docker_2a_20image',['Install Intel® Distribution of OpenVINO™ toolkit for Linux* from a Docker* Image',['../_docs_install_guides_installing_openvino_docker_linux.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20windows_2a_20from_20docker_2a_20image',['Install Intel® Distribution of OpenVINO™ toolkit for Windows* from Docker* Image',['../_docs_install_guides_installing_openvino_docker_windows.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20linux_2a',['Install Intel® Distribution of OpenVINO™ toolkit for Linux*',['../_docs_install_guides_installing_openvino_linux.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20linux_2a_20with_20fpga_20support',['Install Intel® Distribution of OpenVINO™ toolkit for Linux* with FPGA Support',['../_docs_install_guides_installing_openvino_linux_fpga.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20macos_2a',['Install Intel® Distribution of OpenVINO™ toolkit for macOS*',['../_docs_install_guides_installing_openvino_macos.html',1,'']]],
  ['install_20openvino™_20toolkit_20for_20raspbian_2a_20os',['Install OpenVINO™ toolkit for Raspbian* OS',['../_docs_install_guides_installing_openvino_raspbian.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20windows_2a_2010',['Install Intel® Distribution of OpenVINO™ toolkit for Windows* 10',['../_docs_install_guides_installing_openvino_windows.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20linux_2a_20using_20yum_20repository',['Install Intel® Distribution of OpenVINO™ toolkit for Linux* Using YUM Repository',['../_docs_install_guides_installing_openvino_yum.html',1,'']]],
  ['intel®_20movidius™_20vpus_20programming_20guide_20for_20use_20with_20intel®_20distribution_20of_20openvino™_20toolkit',['Intel® Movidius™ VPUs Programming Guide for Use with Intel® Distribution of OpenVINO™ toolkit',['../_docs_install_guides_movidius_programming_guide.html',1,'']]],
  ['intel®_20movidius™_20vpus_20setup_20guide_20for_20use_20with_20intel®_20distribution_20of_20openvino™_20toolkit',['Intel® Movidius™ VPUs Setup Guide for Use with Intel® Distribution of OpenVINO™ toolkit',['../_docs_install_guides_movidius_setup_guide.html',1,'']]],
  ['intermediate_20representation_20notation_20reference_20catalog',['Intermediate Representation Notation Reference Catalog',['../_docs_MO_DG_prepare_model_convert_model_IRLayersCatalogSpec.html',1,'']]],
  ['introduction_20to_20openvino_26trade_3b_20security',['Introduction to OpenVINO&amp;trade; Security',['../_docs_security_guide_introduction.html',1,'']]],
  ['import_20datasets',['Import Datasets',['../_docs_Workbench_DG_Import_Datasets.html',1,'']]],
  ['install_20dl_20workbench_20from_20docker_20hub_2a',['Install DL Workbench from Docker Hub*',['../_docs_Workbench_DG_Install_from_Docker_Hub.html',1,'']]],
  ['install_20dl_20workbench_20from_20dockerfile',['Install DL Workbench from Dockerfile',['../_docs_Workbench_DG_Install_from_Dockerfile.html',1,'']]],
  ['install_20dl_20workbench_20from_20the_20intel_26reg_3b_20distribution_20for_20openvino_26trade_3b_20toolkit_20package',['Install DL Workbench from the Intel&amp;reg; Distribution for OpenVINO&amp;trade; Toolkit Package',['../_docs_Workbench_DG_Install_from_Package.html',1,'']]],
  ['install_20dl_20workbench',['Install DL Workbench',['../_docs_Workbench_DG_Install_Workbench.html',1,'']]],
  ['int8_20quantization',['INT8 Quantization',['../_docs_Workbench_DG_Int_8_Quantization.html',1,'']]],
  ['introduction',['Introduction',['../_docs_Workbench_DG_Introduction.html',1,'']]],
  ['import_20models',['Import Models',['../_docs_Workbench_DG_Select_Models.html',1,'']]],
  ['image_20classification_20python_2a_20sample_20async',['Image Classification Python* Sample Async',['../_inference_engine_ie_bridges_python_sample_classification_sample_async_README.html',1,'']]],
  ['image_20classification_20python_2a_20sample',['Image Classification Python* Sample',['../_inference_engine_ie_bridges_python_sample_classification_sample_README.html',1,'']]],
  ['image_20classification_20c_2b_2b_20sample_20async',['Image Classification C++ Sample Async',['../_inference_engine_samples_classification_sample_async_README.html',1,'']]],
  ['image_2dretrieval_2d0001',['image-retrieval-0001',['../_models_intel_image_retrieval_0001_description_image_retrieval_0001.html',1,'']]],
  ['inceptionv3_2dint8_2dsparse_2dv1_2dtf_2d0001',['inceptionv3-int8-sparse-v1-tf-0001',['../_models_intel_inceptionv3_int8_sparse_v1_tf_0001_description_inceptionv3_int8_sparse_v1_tf_0001.html',1,'']]],
  ['inceptionv3_2dint8_2dsparse_2dv2_2dtf_2d0001',['inceptionv3-int8-sparse-v2-tf-0001',['../_models_intel_inceptionv3_int8_sparse_v2_tf_0001_description_inceptionv3_int8_sparse_v2_tf_0001.html',1,'']]],
  ['inceptionv3_2dint8_2dtf_2d0001',['inceptionv3-int8-tf-0001',['../_models_intel_inceptionv3_int8_tf_0001_description_inceptionv3_int8_tf_0001.html',1,'']]],
  ['instance_2dsegmentation_2dsecurity_2d0010',['instance-segmentation-security-0010',['../_models_intel_instance_segmentation_security_0010_description_instance_segmentation_security_0010.html',1,'']]],
  ['instance_2dsegmentation_2dsecurity_2d0050',['instance-segmentation-security-0050',['../_models_intel_instance_segmentation_security_0050_description_instance_segmentation_security_0050.html',1,'']]],
  ['instance_2dsegmentation_2dsecurity_2d0083',['instance-segmentation-security-0083',['../_models_intel_instance_segmentation_security_0083_description_instance_segmentation_security_0083.html',1,'']]],
  ['builder',['Builder',['../namespaceInferenceEngine_1_1Builder.html',1,'InferenceEngine']]],
  ['cldnnconfigparams',['CLDNNConfigParams',['../namespaceInferenceEngine_1_1CLDNNConfigParams.html',1,'InferenceEngine']]],
  ['dliaconfigparams',['DLIAConfigParams',['../namespaceInferenceEngine_1_1DLIAConfigParams.html',1,'InferenceEngine']]],
  ['dliametrics',['DliaMetrics',['../namespaceInferenceEngine_1_1DliaMetrics.html',1,'InferenceEngine']]],
  ['gnaconfigparams',['GNAConfigParams',['../namespaceInferenceEngine_1_1GNAConfigParams.html',1,'InferenceEngine']]],
  ['heteroconfigparams',['HeteroConfigParams',['../namespaceInferenceEngine_1_1HeteroConfigParams.html',1,'InferenceEngine']]],
  ['i16',['I16',['../classInferenceEngine_1_1Precision.html#ade75bd7073b4aa966c0dda4025bcd0f5acb529fb6affc93bd897333da1756e54b',1,'InferenceEngine::Precision']]],
  ['i32',['I32',['../classInferenceEngine_1_1Precision.html#ade75bd7073b4aa966c0dda4025bcd0f5a5eaacac79637b058ffbb485829175d4c',1,'InferenceEngine::Precision']]],
  ['i64',['I64',['../classInferenceEngine_1_1Precision.html#ade75bd7073b4aa966c0dda4025bcd0f5a76288d38cc52b68fb2127a4eb84b3b80',1,'InferenceEngine::Precision']]],
  ['i8',['I8',['../classInferenceEngine_1_1Precision.html#ade75bd7073b4aa966c0dda4025bcd0f5a8a21a034db6e5da6861616dd892aed2a',1,'InferenceEngine::Precision']]],
  ['i_5fc',['I_C',['../namespaceInferenceEngine.html#a8094f72bf759c368feda7919ce8ef1d6',1,'InferenceEngine']]],
  ['i_5fh',['I_H',['../namespaceInferenceEngine.html#a339223ecfcce8b43223fd8c4afff3b57',1,'InferenceEngine']]],
  ['i_5fn',['I_N',['../namespaceInferenceEngine.html#a5dee71b1ace705d01a7f870ca3e3e0bd',1,'InferenceEngine']]],
  ['i_5fw',['I_W',['../namespaceInferenceEngine.html#ab49e5f757631ca69371b2056613aad1c',1,'InferenceEngine']]],
  ['iallocator',['IAllocator',['../classInferenceEngine_1_1IAllocator.html',1,'InferenceEngine']]],
  ['icnnnetreader',['ICNNNetReader',['../classInferenceEngine_1_1ICNNNetReader.html',1,'InferenceEngine']]],
  ['icnnnetwork',['ICNNNetwork',['../classInferenceEngine_1_1ICNNNetwork.html',1,'InferenceEngine']]],
  ['icnnnetworkstats',['ICNNNetworkStats',['../classInferenceEngine_1_1ICNNNetworkStats.html',1,'InferenceEngine']]],
  ['idx_5ft',['idx_t',['../namespaceInferenceEngine.html#ac1f0c9898ffc82e472561fb05643f51a',1,'InferenceEngine']]],
  ['ie_5fallocator_2ehpp',['ie_allocator.hpp',['../ie__allocator_8hpp.html',1,'']]],
  ['ie_5fapi_2eh',['ie_api.h',['../ie__api_8h.html',1,'']]],
  ['ie_5fassert',['IE_ASSERT',['../ie__exception_8hpp.html#af7eb522bba9d110ae52c00dc1ef2f28a',1,'ie_exception.hpp']]],
  ['ie_5fblob_2eh',['ie_blob.h',['../ie__blob_8h.html',1,'']]],
  ['ie_5fblob_5fiterator_2ehpp',['ie_blob_iterator.hpp',['../ie__blob__iterator_8hpp.html',1,'']]],
  ['ie_5fcnn_5fnet_5freader_2eh',['ie_cnn_net_reader.h',['../ie__cnn__net__reader_8h.html',1,'']]],
  ['ie_5fcnn_5fnetwork_2eh',['ie_cnn_network.h',['../ie__cnn__network_8h.html',1,'']]],
  ['ie_5fcnn_5fnetwork_5fiterator_2ehpp',['ie_cnn_network_iterator.hpp',['../ie__cnn__network__iterator_8hpp.html',1,'']]],
  ['ie_5fcnn_5fnetwork_5ftools_2eh',['ie_cnn_network_tools.h',['../ie__cnn__network__tools_8h.html',1,'']]],
  ['ie_5fcommon_2eh',['ie_common.h',['../ie__common_8h.html',1,'']]],
  ['ie_5fcompound_5fblob_2eh',['ie_compound_blob.h',['../ie__compound__blob_8h.html',1,'']]],
  ['ie_5fcontext_2ehpp',['ie_context.hpp',['../ie__context_8hpp.html',1,'']]],
  ['ie_5fcore_2ehpp',['ie_core.hpp',['../ie__core_8hpp.html',1,'']]],
  ['ie_5fdata_2eh',['ie_data.h',['../ie__data_8h.html',1,'']]],
  ['ie_5fdevice_2ehpp',['ie_device.hpp',['../ie__device_8hpp.html',1,'']]],
  ['ie_5ferror_2ehpp',['ie_error.hpp',['../ie__error_8hpp.html',1,'']]],
  ['ie_5fexception_2ehpp',['ie_exception.hpp',['../ie__exception_8hpp.html',1,'']]],
  ['ie_5fexception_5fconversion_2ehpp',['ie_exception_conversion.hpp',['../ie__exception__conversion_8hpp.html',1,'']]],
  ['ie_5fexecutable_5fnetwork_2ehpp',['ie_executable_network.hpp',['../ie__executable__network_8hpp.html',1,'']]],
  ['ie_5fextension_2eh',['ie_extension.h',['../ie__extension_8h.html',1,'']]],
  ['ie_5ficnn_5fnet_5freader_2eh',['ie_icnn_net_reader.h',['../ie__icnn__net__reader_8h.html',1,'']]],
  ['ie_5ficnn_5fnetwork_2ehpp',['ie_icnn_network.hpp',['../ie__icnn__network_8hpp.html',1,'']]],
  ['ie_5ficnn_5fnetwork_5fstats_2ehpp',['ie_icnn_network_stats.hpp',['../ie__icnn__network__stats_8hpp.html',1,'']]],
  ['ie_5fiexecutable_5fnetwork_2ehpp',['ie_iexecutable_network.hpp',['../ie__iexecutable__network_8hpp.html',1,'']]],
  ['ie_5fiextension_2eh',['ie_iextension.h',['../ie__iextension_8h.html',1,'']]],
  ['ie_5fihetero_5fplugin_2ehpp',['ie_ihetero_plugin.hpp',['../ie__ihetero__plugin_8hpp.html',1,'']]],
  ['ie_5fiinfer_5frequest_2ehpp',['ie_iinfer_request.hpp',['../ie__iinfer__request_8hpp.html',1,'']]],
  ['ie_5fimemory_5fstate_2ehpp',['ie_imemory_state.hpp',['../ie__imemory__state_8hpp.html',1,'']]],
  ['ie_5finfer_5frequest_2ehpp',['ie_infer_request.hpp',['../ie__infer__request_8hpp.html',1,'']]],
  ['ie_5finput_5finfo_2ehpp',['ie_input_info.hpp',['../ie__input__info_8hpp.html',1,'']]],
  ['ie_5firelease_2ehpp',['ie_irelease.hpp',['../ie__irelease_8hpp.html',1,'']]],
  ['ie_5flayers_2eh',['ie_layers.h',['../ie__layers_8h.html',1,'']]],
  ['ie_5flayouts_2eh',['ie_layouts.h',['../ie__layouts_8h.html',1,'']]],
  ['ie_5flocked_5fmemory_2ehpp',['ie_locked_memory.hpp',['../ie__locked__memory_8hpp.html',1,'']]],
  ['ie_5fno_5fcopy_2ehpp',['ie_no_copy.hpp',['../ie__no__copy_8hpp.html',1,'']]],
  ['ie_5fno_5frelease_2ehpp',['ie_no_release.hpp',['../ie__no__release_8hpp.html',1,'']]],
  ['ie_5fparallel_2ehpp',['ie_parallel.hpp',['../ie__parallel_8hpp.html',1,'']]],
  ['ie_5fparse_5ffloat',['ie_parse_float',['../classInferenceEngine_1_1CNNLayer.html#a830772b08ab5b0f7f6defa7317e33783',1,'InferenceEngine::CNNLayer']]],
  ['ie_5fplugin_2ehpp',['ie_plugin.hpp',['../ie__plugin_8hpp.html',1,'']]],
  ['ie_5fplugin_5fconfig_2ehpp',['ie_plugin_config.hpp',['../ie__plugin__config_8hpp.html',1,'']]],
  ['ie_5fplugin_5fcpp_2ehpp',['ie_plugin_cpp.hpp',['../ie__plugin__cpp_8hpp.html',1,'']]],
  ['ie_5fplugin_5fdispatcher_2ehpp',['ie_plugin_dispatcher.hpp',['../ie__plugin__dispatcher_8hpp.html',1,'']]],
  ['ie_5fplugin_5fptr_2ehpp',['ie_plugin_ptr.hpp',['../ie__plugin__ptr_8hpp.html',1,'']]],
  ['ie_5fpre_5fallocator_2ehpp',['ie_pre_allocator.hpp',['../ie__pre__allocator_8hpp.html',1,'']]],
  ['ie_5fprecision_2ehpp',['ie_precision.hpp',['../ie__precision_8hpp.html',1,'']]],
  ['ie_5fpreprocess_2ehpp',['ie_preprocess.hpp',['../ie__preprocess_8hpp.html',1,'']]],
  ['ie_5fprimitive_5finfo_2ehpp',['ie_primitive_info.hpp',['../ie__primitive__info_8hpp.html',1,'']]],
  ['ie_5fserialize_5ffloat',['ie_serialize_float',['../classInferenceEngine_1_1CNNLayer.html#afe311c770dd17382996880052d303bc8',1,'InferenceEngine::CNNLayer']]],
  ['ie_5fso_5floader_2eh',['ie_so_loader.h',['../ie__so__loader_8h.html',1,'']]],
  ['ie_5fso_5fpointer_2ehpp',['ie_so_pointer.hpp',['../ie__so__pointer_8hpp.html',1,'']]],
  ['ie_5ftensor_5finfo_2ehpp',['ie_tensor_info.hpp',['../ie__tensor__info_8hpp.html',1,'']]],
  ['ie_5futils_2ehpp',['ie_utils.hpp',['../ie__utils_8hpp.html',1,'']]],
  ['ie_5fversion_2ehpp',['ie_version.hpp',['../ie__version_8hpp.html',1,'']]],
  ['ierrorlistener',['IErrorListener',['../classInferenceEngine_1_1IErrorListener.html',1,'InferenceEngine']]],
  ['iexecutablenetwork',['IExecutableNetwork',['../classInferenceEngine_1_1IExecutableNetwork.html',1,'InferenceEngine']]],
  ['iextension',['IExtension',['../classInferenceEngine_1_1IExtension.html',1,'InferenceEngine']]],
  ['iheterodeviceloader',['IHeteroDeviceLoader',['../classInferenceEngine_1_1IHeteroDeviceLoader.html',1,'InferenceEngine']]],
  ['iheteroinferenceplugin',['IHeteroInferencePlugin',['../classInferenceEngine_1_1IHeteroInferencePlugin.html',1,'InferenceEngine']]],
  ['iinferenceplugin',['IInferencePlugin',['../classInferenceEngine_1_1IInferencePlugin.html',1,'InferenceEngine']]],
  ['iinferrequest',['IInferRequest',['../classInferenceEngine_1_1IInferRequest.html',1,'InferenceEngine']]],
  ['ilayer',['ILayer',['../classInferenceEngine_1_1ILayer.html',1,'InferenceEngine']]],
  ['ilayerexecimpl',['ILayerExecImpl',['../classInferenceEngine_1_1ILayerExecImpl.html',1,'InferenceEngine']]],
  ['ilayerimpl',['ILayerImpl',['../classInferenceEngine_1_1ILayerImpl.html',1,'InferenceEngine']]],
  ['ilayerimplfactory',['ILayerImplFactory',['../classInferenceEngine_1_1ILayerImplFactory.html',1,'InferenceEngine']]],
  ['imemorystate',['IMemoryState',['../classInferenceEngine_1_1IMemoryState.html',1,'InferenceEngine']]],
  ['importnetwork',['ImportNetwork',['../classInferenceEngine_1_1InferencePlugin.html#ab8a7dcd1dbf960261fb91efe33457286',1,'InferenceEngine::InferencePlugin::ImportNetwork()'],['../classInferenceEngine_1_1Core.html#a3947f56fe979b09c1d959638fb815701',1,'InferenceEngine::Core::ImportNetwork()'],['../classInferenceEngine_1_1IInferencePlugin.html#a40cac4eba512cf96231f05b3caaff019',1,'InferenceEngine::IInferencePlugin::ImportNetwork()']]],
  ['inconfs',['inConfs',['../structInferenceEngine_1_1LayerConfig.html#a4e8a1dd13843a80704a093c2b138ebe3',1,'InferenceEngine::LayerConfig']]],
  ['inetwork',['INetwork',['../classInferenceEngine_1_1INetwork.html',1,'InferenceEngine']]],
  ['inetwotkiterator',['INetwotkIterator',['../classInferenceEngine_1_1INetwotkIterator.html',1,'InferenceEngine']]],
  ['infer',['Infer',['../classInferenceEngine_1_1InferRequest.html#a3391ce30894abde730523e9ca9371ce8',1,'InferenceEngine::InferRequest::Infer()'],['../classInferenceEngine_1_1InferencePlugin.html#a70d4e46ade4bc580c7c69e7eeb92274d',1,'InferenceEngine::InferencePlugin::Infer()'],['../classInferenceEngine_1_1IInferRequest.html#a797f06ce79f87c5ff7091a2570a44e0c',1,'InferenceEngine::IInferRequest::Infer()'],['../classInferenceEngine_1_1IInferencePlugin.html#a9d2f325d953d4f7fea65ae9f3188022b',1,'InferenceEngine::IInferencePlugin::Infer(const Blob &amp;input, Blob &amp;result, ResponseDesc *resp) noexcept=0'],['../classInferenceEngine_1_1IInferencePlugin.html#a250c56d6fdea13fbeab3e11e185f014f',1,'InferenceEngine::IInferencePlugin::Infer(const BlobMap &amp;input, BlobMap &amp;result, ResponseDesc *resp) noexcept=0']]],
  ['inference_5fengine_2ehpp',['inference_engine.hpp',['../inference__engine_8hpp.html',1,'']]],
  ['inference_5fextension_5fapi',['INFERENCE_EXTENSION_API',['../ie__iextension_8h.html#ab1cee1a7b68db6db85973663602e8b02',1,'ie_iextension.h']]],
  ['inference_5fplugin_5fapi',['INFERENCE_PLUGIN_API',['../ie__plugin_8hpp.html#ac7863d381d701e306aef004822ebced6',1,'ie_plugin.hpp']]],
  ['inferenceengine',['InferenceEngine',['../namespaceInferenceEngine.html',1,'']]],
  ['inferenceenginepluginptr',['InferenceEnginePluginPtr',['../namespaceInferenceEngine.html#a31b044b371eef8faf8751c9d9d26bd7c',1,'InferenceEngine']]],
  ['inferenceengineprofileinfo',['InferenceEngineProfileInfo',['../structInferenceEngine_1_1InferenceEngineProfileInfo.html',1,'InferenceEngine']]],
  ['inferenceplugin',['InferencePlugin',['../classInferenceEngine_1_1InferencePlugin.html#a54b2a5f863c22fd2d734d7e9a54322a6',1,'InferenceEngine::InferencePlugin::InferencePlugin()=default'],['../classInferenceEngine_1_1InferencePlugin.html#af345793ec44d2e3c50561b1dcfd61a4a',1,'InferenceEngine::InferencePlugin::InferencePlugin(const InferenceEnginePluginPtr &amp;pointer)']]],
  ['inferenceplugin',['InferencePlugin',['../classInferenceEngine_1_1InferencePlugin.html',1,'InferenceEngine']]],
  ['infernotstarted',['InferNotStarted',['../classInferenceEngine_1_1InferNotStarted.html',1,'InferenceEngine']]],
  ['inferrequest',['InferRequest',['../classInferenceEngine_1_1InferRequest.html',1,'InferenceEngine']]],
  ['inferrequest',['InferRequest',['../classInferenceEngine_1_1InferRequest.html#a47c1d4d15e66d7923e59551d70f8ca74',1,'InferenceEngine::InferRequest::InferRequest()=default'],['../classInferenceEngine_1_1InferRequest.html#a236f5a941f5e155f61d48134a00082a0',1,'InferenceEngine::InferRequest::InferRequest(IInferRequest::Ptr request, InferenceEnginePluginPtr plg={})']]],
  ['infershapes',['inferShapes',['../classInferenceEngine_1_1IShapeInferImpl.html#a2a50ceecd9eee8a66ea904ffde182abf',1,'InferenceEngine::IShapeInferImpl::inferShapes(const std::vector&lt; Blob::CPtr &gt; &amp;, const std::map&lt; std::string, std::string &gt; &amp;, const std::map&lt; std::string, Blob::Ptr &gt; &amp;, std::vector&lt; SizeVector &gt; &amp;, ResponseDesc *) noexcept'],['../classInferenceEngine_1_1IShapeInferImpl.html#a3a60a8308d33864a1f221eebc4410b62',1,'InferenceEngine::IShapeInferImpl::inferShapes(const std::vector&lt; SizeVector &gt; &amp;, const std::map&lt; std::string, std::string &gt; &amp;, const std::map&lt; std::string, Blob::Ptr &gt; &amp;, std::vector&lt; SizeVector &gt; &amp;, ResponseDesc *) noexcept']]],
  ['init',['init',['../classInferenceEngine_1_1ILayerImpl.html#a5b060b1c8a6e75e7d4ca57065479543c',1,'InferenceEngine::ILayerImpl::init()'],['../classInferenceEngine_1_1PreProcessInfo.html#a064ac8a3065908e633ccf7ade268e194',1,'InferenceEngine::PreProcessInfo::init()']]],
  ['inplace',['inPlace',['../structInferenceEngine_1_1DataConfig.html#afe6f8028187d9e6e4473a51b0a637bc3',1,'InferenceEngine::DataConfig']]],
  ['input',['input',['../classInferenceEngine_1_1CNNLayer.html#a864d9dcd5ec644df5794b0ac5f47af5f',1,'InferenceEngine::CNNLayer']]],
  ['input_5fstreaming',['INPUT_STREAMING',['../namespaceInferenceEngine_1_1DliaMetrics.html#a26aa1d57e1a717517149aeb5f7029680',1,'InferenceEngine::DliaMetrics']]],
  ['inputinfo',['InputInfo',['../classInferenceEngine_1_1InputInfo.html',1,'InferenceEngine']]],
  ['inputlayer',['InputLayer',['../classInferenceEngine_1_1Builder_1_1InputLayer.html',1,'InferenceEngine::Builder']]],
  ['inputlayer',['InputLayer',['../classInferenceEngine_1_1Builder_1_1InputLayer.html#a8d00af29d3e6f5126b1c60eb60fc984b',1,'InferenceEngine::Builder::InputLayer::InputLayer(const std::string &amp;name=&quot;&quot;)'],['../classInferenceEngine_1_1Builder_1_1InputLayer.html#ae955ff4ab465926829e606cd440234b6',1,'InferenceEngine::Builder::InputLayer::InputLayer(const Layer::Ptr &amp;layer)'],['../classInferenceEngine_1_1Builder_1_1InputLayer.html#a642fcf4ba446d8fa38e490a799ad1c76',1,'InferenceEngine::Builder::InputLayer::InputLayer(const Layer::CPtr &amp;layer)']]],
  ['inputs',['inputs',['../structInferenceEngine_1_1PrimitiveInfo.html#ab256ae14eafc1a9e2729f74e6ef3711d',1,'InferenceEngine::PrimitiveInfo']]],
  ['inputsdatamap',['InputsDataMap',['../namespaceInferenceEngine.html#a08270747275eb79985154365aa782a2a',1,'InferenceEngine']]],
  ['inputshapes',['InputShapes',['../classInferenceEngine_1_1ICNNNetwork.html#a8bcef7f638f6588a672a32080047ff1d',1,'InferenceEngine::ICNNNetwork']]],
  ['inputto',['inputTo',['../classInferenceEngine_1_1Data.html#a10098f1512e9fdec72e35ec6ada6f9c7',1,'InferenceEngine::Data']]],
  ['insdata',['insData',['../classInferenceEngine_1_1CNNLayer.html#a1053f3f44f7492f79d755c8afe1e83b7',1,'InferenceEngine::CNNLayer']]],
  ['ipreallocatedmemory',['iPreAllocatedMemory',['../structInferenceEngine_1_1PrimitiveInfo.html#a25058b65db8c7b4802f1a412ea3f7564',1,'InferenceEngine::PrimitiveInfo']]],
  ['is',['is',['../classInferenceEngine_1_1Blob.html#aa07152ba7c9910abab46a7e8e58323bc',1,'InferenceEngine::Blob::is() noexcept'],['../classInferenceEngine_1_1Blob.html#a74f56a3007a5dbabd8acda5e11d9568c',1,'InferenceEngine::Blob::is() const noexcept'],['../classInferenceEngine_1_1Parameter.html#a5e099158b85b6a7360a780110f1230b6',1,'InferenceEngine::Parameter::is()']]],
  ['is_5ffloat',['is_float',['../classInferenceEngine_1_1Precision.html#a75120c3755cd82bca4218d61bae40248',1,'InferenceEngine::Precision']]],
  ['isempty',['isEmpty',['../classInferenceEngine_1_1ICNNNetworkStats.html#a5a5689c618c942f330a18552b349ccd7',1,'InferenceEngine::ICNNNetworkStats']]],
  ['ishapeinferextension',['IShapeInferExtension',['../classInferenceEngine_1_1IShapeInferExtension.html',1,'InferenceEngine']]],
  ['ishapeinferimpl',['IShapeInferImpl',['../classInferenceEngine_1_1IShapeInferImpl.html',1,'InferenceEngine']]],
  ['isinitialized',['isInitialized',['../classInferenceEngine_1_1Data.html#ae306efbe9612f9908fa2e3bf581b0607',1,'InferenceEngine::Data']]],
  ['isparsesuccess',['isParseSuccess',['../classInferenceEngine_1_1CNNNetReader.html#a640153f401d52e390efd762099f88d60',1,'InferenceEngine::CNNNetReader::isParseSuccess()'],['../classInferenceEngine_1_1ICNNNetReader.html#a9fce3a3b9df7587c3290723a9642297b',1,'InferenceEngine::ICNNNetReader::isParseSuccess()']]],
  ['iterator',['iterator',['../classInferenceEngine_1_1Builder_1_1Network.html#a4b27332776341fe5958fbc54802d01d0',1,'InferenceEngine::Builder::Network']]],
  ['metrics',['Metrics',['../namespaceInferenceEngine_1_1Metrics.html',1,'InferenceEngine']]],
  ['multideviceconfigparams',['MultiDeviceConfigParams',['../namespaceInferenceEngine_1_1MultiDeviceConfigParams.html',1,'InferenceEngine']]],
  ['pluginconfigparams',['PluginConfigParams',['../namespaceInferenceEngine_1_1PluginConfigParams.html',1,'InferenceEngine']]],
  ['vpuconfigparams',['VPUConfigParams',['../namespaceInferenceEngine_1_1VPUConfigParams.html',1,'InferenceEngine']]]
];
