var searchData=
[
  ['interactive_20face_20detection_20c_2b_2b_20demo',['Interactive Face Detection C++ Demo',['../_demos_interactive_face_detection_demo_README.html',1,'']]],
  ['interactive_20face_20recognition_20demo',['Interactive Face Recognition Demo',['../_demos_python_demos_face_recognition_demo_README.html',1,'']]],
  ['image_20retrieval_20python_2a_20demo',['Image Retrieval Python* Demo',['../_demos_python_demos_image_retrieval_demo_README.html',1,'']]],
  ['instance_20segmentation_20python_2a_20demo',['Instance Segmentation Python* Demo',['../_demos_python_demos_instance_segmentation_demo_README.html',1,'']]],
  ['image_20segmentation_20python_2a_20demo',['Image Segmentation Python* Demo',['../_demos_python_demos_segmentation_demo_README.html',1,'']]],
  ['inference_20engine_20demos',['Inference Engine Demos',['../_demos_README.html',1,'']]],
  ['image_20segmentation_20c_2b_2b_20demo',['Image Segmentation C++ Demo',['../_demos_segmentation_demo_README.html',1,'']]],
  ['inference_20engine_20api_20changes_20history',['Inference Engine API Changes History',['../_docs_IE_DG_API_Changes.html',1,'']]],
  ['inference_20engine_20developer_20guide',['Inference Engine Developer Guide',['../_docs_IE_DG_Deep_Learning_Inference_Engine_DevGuide.html',1,'']]],
  ['introduction_20to_20inference_20engine',['Introduction to Inference Engine',['../_docs_IE_DG_inference_engine_intro.html',1,'']]],
  ['introduction_20to_20inference_20engine_20device_20query_20api',['Introduction to Inference Engine Device Query API',['../_docs_IE_DG_InferenceEngine_QueryAPI.html',1,'']]],
  ['integrate_20the_20inference_20engine_20with_20your_20application',['Integrate the Inference Engine with Your Application',['../_docs_IE_DG_Integrate_with_customer_application_new_API.html',1,'']]],
  ['inference_20engine_20kernels_20extensibility',['Inference Engine Kernels Extensibility',['../_docs_IE_DG_Integrate_your_kernels_into_IE.html',1,'']]],
  ['introduction_20to_20the_20performance_20topics',['Introduction to the Performance Topics',['../_docs_IE_DG_Intro_to_Performance.html',1,'']]],
  ['introduction_20to_20intel®_20deep_20learning_20deployment_20toolkit',['Introduction to Intel® Deep Learning Deployment Toolkit',['../_docs_IE_DG_Introduction.html',1,'']]],
  ['inference_20engine_20memory_20primitives',['Inference Engine Memory primitives',['../_docs_IE_DG_Memory_primitives.html',1,'']]],
  ['introduction_20to_20the_20inference_20engine_20neural_20network_20builder',['Introduction to the Inference Engine Neural Network Builder',['../_docs_IE_DG_NNBuilder.html',1,'']]],
  ['inference_20engine_20samples',['Inference Engine Samples',['../_docs_IE_DG_Samples_Overview.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20linux_2a_20using_20apt_20repository',['Install Intel® Distribution of OpenVINO™ toolkit for Linux* Using APT Repository',['../_docs_install_guides_installing_openvino_apt.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20linux_2a_20from_20a_20docker_2a_20image',['Install Intel® Distribution of OpenVINO™ toolkit for Linux* from a Docker* Image',['../_docs_install_guides_installing_openvino_docker_linux.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20windows_2a_20from_20docker_2a_20image',['Install Intel® Distribution of OpenVINO™ toolkit for Windows* from Docker* Image',['../_docs_install_guides_installing_openvino_docker_windows.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20linux_2a',['Install Intel® Distribution of OpenVINO™ toolkit for Linux*',['../_docs_install_guides_installing_openvino_linux.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20linux_2a_20with_20fpga_20support',['Install Intel® Distribution of OpenVINO™ toolkit for Linux* with FPGA Support',['../_docs_install_guides_installing_openvino_linux_fpga.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20macos_2a',['Install Intel® Distribution of OpenVINO™ toolkit for macOS*',['../_docs_install_guides_installing_openvino_macos.html',1,'']]],
  ['install_20openvino™_20toolkit_20for_20raspbian_2a_20os',['Install OpenVINO™ toolkit for Raspbian* OS',['../_docs_install_guides_installing_openvino_raspbian.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20windows_2a_2010',['Install Intel® Distribution of OpenVINO™ toolkit for Windows* 10',['../_docs_install_guides_installing_openvino_windows.html',1,'']]],
  ['install_20intel®_20distribution_20of_20openvino™_20toolkit_20for_20linux_2a_20using_20yum_20repository',['Install Intel® Distribution of OpenVINO™ toolkit for Linux* Using YUM Repository',['../_docs_install_guides_installing_openvino_yum.html',1,'']]],
  ['intel®_20movidius™_20vpus_20programming_20guide_20for_20use_20with_20intel®_20distribution_20of_20openvino™_20toolkit',['Intel® Movidius™ VPUs Programming Guide for Use with Intel® Distribution of OpenVINO™ toolkit',['../_docs_install_guides_movidius_programming_guide.html',1,'']]],
  ['intel®_20movidius™_20vpus_20setup_20guide_20for_20use_20with_20intel®_20distribution_20of_20openvino™_20toolkit',['Intel® Movidius™ VPUs Setup Guide for Use with Intel® Distribution of OpenVINO™ toolkit',['../_docs_install_guides_movidius_setup_guide.html',1,'']]],
  ['intermediate_20representation_20notation_20reference_20catalog',['Intermediate Representation Notation Reference Catalog',['../_docs_MO_DG_prepare_model_convert_model_IRLayersCatalogSpec.html',1,'']]],
  ['introduction_20to_20openvino_26trade_3b_20security',['Introduction to OpenVINO&amp;trade; Security',['../_docs_security_guide_introduction.html',1,'']]],
  ['import_20datasets',['Import Datasets',['../_docs_Workbench_DG_Import_Datasets.html',1,'']]],
  ['install_20dl_20workbench_20from_20docker_20hub_2a',['Install DL Workbench from Docker Hub*',['../_docs_Workbench_DG_Install_from_Docker_Hub.html',1,'']]],
  ['install_20dl_20workbench_20from_20dockerfile',['Install DL Workbench from Dockerfile',['../_docs_Workbench_DG_Install_from_Dockerfile.html',1,'']]],
  ['install_20dl_20workbench_20from_20the_20intel_26reg_3b_20distribution_20for_20openvino_26trade_3b_20toolkit_20package',['Install DL Workbench from the Intel&amp;reg; Distribution for OpenVINO&amp;trade; Toolkit Package',['../_docs_Workbench_DG_Install_from_Package.html',1,'']]],
  ['install_20dl_20workbench',['Install DL Workbench',['../_docs_Workbench_DG_Install_Workbench.html',1,'']]],
  ['int8_20quantization',['INT8 Quantization',['../_docs_Workbench_DG_Int_8_Quantization.html',1,'']]],
  ['introduction',['Introduction',['../_docs_Workbench_DG_Introduction.html',1,'']]],
  ['import_20models',['Import Models',['../_docs_Workbench_DG_Select_Models.html',1,'']]],
  ['image_20classification_20python_2a_20sample_20async',['Image Classification Python* Sample Async',['../_inference_engine_ie_bridges_python_sample_classification_sample_async_README.html',1,'']]],
  ['image_20classification_20python_2a_20sample',['Image Classification Python* Sample',['../_inference_engine_ie_bridges_python_sample_classification_sample_README.html',1,'']]],
  ['image_20classification_20c_2b_2b_20sample_20async',['Image Classification C++ Sample Async',['../_inference_engine_samples_classification_sample_async_README.html',1,'']]],
  ['image_2dretrieval_2d0001',['image-retrieval-0001',['../_models_intel_image_retrieval_0001_description_image_retrieval_0001.html',1,'']]],
  ['inceptionv3_2dint8_2dsparse_2dv1_2dtf_2d0001',['inceptionv3-int8-sparse-v1-tf-0001',['../_models_intel_inceptionv3_int8_sparse_v1_tf_0001_description_inceptionv3_int8_sparse_v1_tf_0001.html',1,'']]],
  ['inceptionv3_2dint8_2dsparse_2dv2_2dtf_2d0001',['inceptionv3-int8-sparse-v2-tf-0001',['../_models_intel_inceptionv3_int8_sparse_v2_tf_0001_description_inceptionv3_int8_sparse_v2_tf_0001.html',1,'']]],
  ['inceptionv3_2dint8_2dtf_2d0001',['inceptionv3-int8-tf-0001',['../_models_intel_inceptionv3_int8_tf_0001_description_inceptionv3_int8_tf_0001.html',1,'']]],
  ['instance_2dsegmentation_2dsecurity_2d0010',['instance-segmentation-security-0010',['../_models_intel_instance_segmentation_security_0010_description_instance_segmentation_security_0010.html',1,'']]],
  ['instance_2dsegmentation_2dsecurity_2d0050',['instance-segmentation-security-0050',['../_models_intel_instance_segmentation_security_0050_description_instance_segmentation_security_0050.html',1,'']]],
  ['instance_2dsegmentation_2dsecurity_2d0083',['instance-segmentation-security-0083',['../_models_intel_instance_segmentation_security_0083_description_instance_segmentation_security_0083.html',1,'']]]
];
