var menudata={children:[
{text:'OpenVINO Home',url:'index.html'},
{text:'GETTING STARTED',url:'index.html',children:[
{text:'OpenVINO Toolkit Overview',url:'index.html'},
{text:'Install Intel® Distribution of OpenVINO™ toolkit for Linux* OS',url:'_docs_install_guides_installing_openvino_linux.html',children:[
{text:'Configuration Guide for the Intel® Distribution of OpenVINO™ toolkit and the Intel® Vision Accelerator Design with Intel® Movidius™ VPUs on Linux*',url:'_docs_install_guides_installing_openvino_linux_ivad_vpu.html'}]},
{text:'Install Intel® Distribution of OpenVINO™ toolkit for Linux with FPGA Support',url:'_docs_install_guides_installing_openvino_linux_fpga.html',children:[
{text:'Configuration Guide for OpenVINO 2019R3 and the Intel® Vision Accelerator Design with an Intel® Arria 10 FPGA SG1 or SG2 (IEIs Mustang-F100-A10) on Linux',url:'_docs_install_guides_VisionAcceleratorFPGA_Configure_2019R3.html'},
{text:'Configuration Guide for OpenVINO 2019R1 and the Intel® Vision Accelerator Design with an Intel® Arria 10 FPGA (IEIs Mustang-F100-A10) on Linux',url:'_docs_install_guides_VisionAcceleratorFPGA_Configure_2019R1.html'},
{text:'Configuration Guide for OpenVINO 2019R1/2019R2 and the Intel® Programmable Acceleration Card with Intel Arria® 10 GX FPGA on Linux',url:'_docs_install_guides_PAC_Configure_2019RX.html'},
{text:'Configuration Guide for OpenVINO 2018R5 and the Intel® Vision Accelerator Design with an Intel® Arria 10 FPGA (IEIs Mustang-F100-A10) on Linux',url:'_docs_install_guides_VisionAcceleratorFPGA_Configure_2018R5.html'},
{text:'Configuration Guide for OpenVINO 2018R5 and the Intel® Programmable Acceleration Card with Intel Arria® 10 GX FPGA on CentOS',url:'_docs_install_guides_PAC_Configure_2018R5.html'}]},
{text:'Install Intel® Distribution of OpenVINO™ toolkit for macOS*',url:'_docs_install_guides_installing_openvino_macos.html'},
{text:'Install Intel® Distribution of OpenVINO™ toolkit for Raspbian* OS',url:'_docs_install_guides_installing_openvino_raspbian.html'},
{text:'Install Intel® Distribution of OpenVINO™ toolkit for Windows* 10',url:'_docs_install_guides_installing_openvino_windows.html'},
{text:'Intel® Movidius™ VPUs Setup Guide for Use with Intel® Distribution of OpenVINO™ toolkit',url:'_docs_install_guides_movidius_setup_guide.html'},
{text:'Intel® Movidius™ VPUs Programming Guide for Use with Intel® Distribution of OpenVINO™ toolkit',url:'_docs_install_guides_movidius_programming_guide.html'},
{text:'Install Intel® Distribution of OpenVINO™ toolkit for Linux* from a Docker* Image',url:'_docs_install_guides_installing_openvino_docker_linux.html'},
{text:'Install Intel® Distribution of OpenVINO™ toolkit for Windows* from a Docker* Image',url:'_docs_install_guides_installing_openvino_docker_windows.html'},
{text:'Install Intel® Distribution of OpenVINO™ toolkit for Linux* Using APT Repository',url:'_docs_install_guides_installing_openvino_apt.html'},
{text:'Install Intel® Distribution of OpenVINO™ toolkit for Linux* Using YUM Repository',url:'_docs_install_guides_installing_openvino_yum.html'},
{text:'Deploy Inference Engine Components to Target Host Using Deployment Manager',url:'_docs_install_guides_deployment_manager_tool.html'}]},
{text:'HOW TOs',url:'_docs_how_tos_how_to_links.html',children:[
{text:'\"Hot Topic\" How-To Links',url:'_docs_how_tos_how_to_links.html'},
{text:'Custom Layers Guide',url:'_docs_HOWTO_Custom_Layers_Guide.html'}]},
{text:'GUIDES',url:'_docs_IE_DG_Introduction.html',children:[
{text:'Overview',url:'_docs_IE_DG_Introduction.html'},
{text:'GUIDES',url:'_docs_IE_DG_Introduction.html',children:[
{text:'Model Optimizer Developer Guide',url:'_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html',children:[
{text:'Preparing and Optimizing Your Trained Model',url:'_docs_MO_DG_prepare_model_Prepare_Trained_Model.html',children:[
{text:'Configuring the Model Optimizer',url:'_docs_MO_DG_prepare_model_Config_Model_Optimizer.html'},
{text:'Converting a Model to Intermediate Representation (IR)',url:'_docs_MO_DG_prepare_model_convert_model_Converting_Model.html',children:[
{text:'Converting a Model Using General Conversion Parameters',url:'_docs_MO_DG_prepare_model_convert_model_Converting_Model_General.html'},
{text:'Converting a Caffe* Model',url:'_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_Caffe.html'},
{text:'Converting a TensorFlow* Model',url:'_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html',children:[
{text:'Converting YOLO* Models from DarkNet to the Intermediate Representation',url:'_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html'},
{text:'Converting FaceNet Models from TensorFlow',url:'_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_FaceNet_From_Tensorflow.html'},
{text:'Converting Neural Collaborative Filtering Model from TensorFlow',url:'_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_NCF_From_Tensorflow.html'},
{text:'Converting DeepSpeech Model from TensorFlow',url:'_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_DeepSpeech_From_Tensorflow.html'},
{text:'Converting Language Model on One Billion Word Benchmark from TensorFlow',url:'_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_lm_1b_From_Tensorflow.html'},
{text:'Converting TensorFlow* Object Detection API Models',url:'_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html'},
{text:'Converting TensorFlow*-Slim Image Classification Model Library Models',url:'_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Slim_Library_Models.html'},
{text:'Converting CRNN Model from TensorFlow',url:'_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_CRNN_From_Tensorflow.html'},
{text:'Converting GNMT from TensorFlow',url:'_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_GNMT_From_Tensorflow.html'},
{text:'Converting BERT from TensorFlow',url:'_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_BERT_From_Tensorflow.html'}]},
{text:'Converting a MXNet* Model',url:'_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_MxNet.html',children:[
{text:'Converting a Style Transfer Model from MXNet',url:'_docs_MO_DG_prepare_model_convert_model_mxnet_specific_Convert_Style_Transfer_From_MXNet.html'}]},
{text:'Converting Your Kaldi* Model',url:'_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_Kaldi.html',children:[
{text:'Convert Kaldi* ASpIRE Chain Time Delay Neural Network (TDNN) Model to the Intermediate Representation',url:'_docs_MO_DG_prepare_model_convert_model_kaldi_specific_Aspire_Tdnn_Model.html'}]},
{text:'Converting Your ONNX* Model',url:'_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html'},
{text:'Model Optimizations Techniques',url:'_docs_MO_DG_prepare_model_Model_Optimization_Techniques.html'},
{text:'Cutting off Parts of a Model',url:'_docs_MO_DG_prepare_model_convert_model_Cutting_Model.html'},
{text:'Sub-graph Replacement in Model Optimizer',url:'_docs_MO_DG_prepare_model_customize_model_optimizer_Subgraph_Replacement_Model_Optimizer.html',children:[
{text:'(Deprecated) Case-Study: Converting SSD models created with the TensorFlow* Object Detection API',url:'_docs_MO_DG_prepare_model_customize_model_optimizer_TensorFlow_SSD_ObjectDetection_API.html'},
{text:'(Deprecated) Case-Study: Converting Faster R-CNN models created with the TensorFlow* Object Detection API',url:'_docs_MO_DG_prepare_model_customize_model_optimizer_TensorFlow_Faster_RCNN_ObjectDetection_API.html'}]},
{text:'Supported Framework Layers',url:'_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html'},
{text:'IR Notation Reference',url:'_docs_MO_DG_prepare_model_convert_model_IRLayersCatalogSpec.html'}]},
{text:'Custom Layers in Model Optimizer',url:'_docs_MO_DG_prepare_model_customize_model_optimizer_Customize_Model_Optimizer.html',children:[
{text:'Extending Model Optimizer with New Primitives',url:'_docs_MO_DG_prepare_model_customize_model_optimizer_Extending_Model_Optimizer_with_New_Primitives.html'},
{text:'Extending MXNet Model Optimizer with New Primitives',url:'_docs_MO_DG_prepare_model_customize_model_optimizer_Extending_MXNet_Model_Optimizer_with_New_Primitives.html'},
{text:'Using Automatic Generation for Creating Model Optimizer and Inference Engine Extension',url:'_docs_MO_DG_prepare_model_customize_model_optimizer_Extension_generation.html'},
{text:'Legacy Mode for Caffe* Custom Layers',url:'_docs_MO_DG_prepare_model_customize_model_optimizer_Legacy_Mode_for_Caffe_Custom_Layers.html'},
{text:'Offloading Sub-Graph Inference',url:'_docs_MO_DG_prepare_model_customize_model_optimizer_Offloading_Sub_Graph_Inference.html'}]}]},
{text:'Model Optimizer Frequently Asked Questions',url:'_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html'},
{text:'Known Issues',url:'_docs_MO_DG_Known_Issues_Limitations.html'}]},
{text:'Inference Engine Developer Guide',url:'_docs_IE_DG_Deep_Learning_Inference_Engine_DevGuide.html',children:[
{text:'Introduction to Inference Engine',url:'_docs_IE_DG_inference_engine_intro.html'},
{text:'Inference Engine API Changes History',url:'_docs_IE_DG_API_Changes.html'},
{text:'Inference Engine Memory primitives',url:'_docs_IE_DG_Memory_primitives.html'},
{text:'Inference Engine Device Query API',url:'_docs_IE_DG_InferenceEngine_QueryAPI.html'},
{text:'Inference Engine Kernels Extensibility',url:'_docs_IE_DG_Integrate_your_kernels_into_IE.html'},
{text:'Integrate the Inference Engine with Your Application',url:'_docs_IE_DG_Integrate_with_customer_application_new_API.html'},
{text:'Migration from Inference Engine Plugin API to Core API',url:'_docs_IE_DG_Migration_CoreAPI.html'},
{text:'Introduction to Performance Topics',url:'_docs_IE_DG_Intro_to_Performance.html'},
{text:'Inference Engine Python* API Overview',url:'_inference_engine_ie_bridges_python_docs_api_overview.html'},
{text:'Introduction to the Inference Engine Neural Network Builder',url:'_docs_IE_DG_NNBuilder.html'},
{text:'Using Dynamic Batching Feature',url:'_docs_IE_DG_DynamicBatching.html'},
{text:'Using Static Shape Infer Feature',url:'_docs_IE_DG_ShapeInference.html'},
{text:'Using GPU kernels tuning',url:'_docs_IE_DG_GPU_Kernels_Tuning.html'},
{text:'Using Low-Precision 8-bit Integer Inference',url:'_docs_IE_DG_Int8Inference.html',children:[
{text:'Using Calibration Tool to Prepare Model Executed in Low-Precision 8-bit Integer Computation',url:'_inference_engine_tools_calibration_tool_README.html'}]},
{text:'Utilities to Validate Your Converted Model',url:'usergroup0.html',children:[
{text:'Using Cross Check Tool for Per-Layer Comparison Between Plugins',url:'_docs_IE_DG_Cross_Check_Tool.html'}]},
{text:'Supported Devices',url:'_docs_IE_DG_supported_plugins_Supported_Devices.html',children:[
{text:'GPU Plugin',url:'_docs_IE_DG_supported_plugins_CL_DNN.html'},
{text:'CPU Plugin',url:'_docs_IE_DG_supported_plugins_CPU.html',children:[
{text:'CPU Extensions',url:'_inference_engine_src_extension_README.html'}]},
{text:'FPGA Plugin',url:'_docs_IE_DG_supported_plugins_FPGA.html'},
{text:'VPU Plugins',url:'_docs_IE_DG_supported_plugins_VPU.html',children:[
{text:'MYRIAD Plugin ',url:'_docs_IE_DG_supported_plugins_MYRIAD.html'},
{text:'HDDL Plugin ',url:'_docs_IE_DG_supported_plugins_HDDL.html'}]},
{text:'Heterogeneous Plugin',url:'_docs_IE_DG_supported_plugins_HETERO.html'},
{text:'Multi-Device Plugin',url:'_docs_IE_DG_supported_plugins_MULTI.html'},
{text:'GNA Plugin',url:'_docs_IE_DG_supported_plugins_GNA.html'}]},
{text:'Known Issues',url:'_docs_IE_DG_Known_Issues_Limitations.html'},
{text:'Optimization Notice',url:'_docs_IE_DG_Optimization_notice.html'},
{text:'Legal Information',url:'_docs_IE_DG_Legal_Information.html'},
{text:'Glossary',url:'_docs_IE_DG_Glossary.html'}]},
{text:'Deep Learning Workbench Developer Guide',url:'_docs_Workbench_DG_Introduction.html',children:[
{text:'Introduction',url:'_docs_Workbench_DG_Introduction.html'},
{text:'Get Started',url:'_docs_Workbench_DG_Install_Workbench.html',children:[
{text:'Install DL Workbench',url:'_docs_Workbench_DG_Install_Workbench.html',children:[
{text:'Install from Docker Hub*',url:'_docs_Workbench_DG_Install_from_Docker_Hub.html'},
{text:'Install from the Intel® Distribution of OpenVINO™ Toolkit Package',url:'_docs_Workbench_DG_Install_from_Package.html'},
{text:'Install from Dockerfile',url:'_docs_Workbench_DG_Install_from_Dockerfile.html'}]},
{text:'Work with Models and Sample Datasets',url:'_docs_Workbench_DG_Work_with_Models_and_Sample_Datasets.html',children:[
{text:'Select Models',url:'_docs_Workbench_DG_Select_Model.html',children:[
{text:'Import Models',url:'_docs_Workbench_DG_Select_Models.html'}]},
{text:'Select Datasets',url:'_docs_Workbench_DG_Select_Datasets.html',children:[
{text:'Import Datasets',url:'_docs_Workbench_DG_Import_Datasets.html'},
{text:'Generate Datasets',url:'_docs_Workbench_DG_Generate_Datasets.html'}]},
{text:'Dataset Types',url:'_docs_Workbench_DG_Dataset_Types.html'},
{text:'Download and Cut Datasets',url:'_docs_Workbench_DG_Download_and_Cut_Datasets.html'}]}]},
{text:'Measure and Interpret Model Performance',url:'_docs_Workbench_DG_Run_Single_Inference.html',children:[
{text:'Run Single Inference',url:'_docs_Workbench_DG_Run_Single_Inference.html'},
{text:'Run Range of Inferences',url:'_docs_Workbench_DG_Run_Range_of_Inferences.html'},
{text:'View Inference Results',url:'_docs_Workbench_DG_View_Inference_Results.html',children:[
{text:'Visualize Model',url:'_docs_Workbench_DG_Visualize_Model.html'}]}]},
{text:'Tune Model for Enhanced Performance',url:'_docs_Workbench_DG_Int_8_Quantization.html',children:[
{text:'INT8 Quantization',url:'_docs_Workbench_DG_Int_8_Quantization.html'},
{text:'Winograd Algorithmic Tuning',url:'_docs_Workbench_DG_Winograd_Algorithmic_Tuning.html'},
{text:'Compare Performance between Two Versions of Models',url:'_docs_Workbench_DG_Compare_Performance_between_Two_Versions_of_Models.html'}]},
{text:'Accuracy Measurements',url:'_docs_Workbench_DG_Measure_Accuracy.html',children:[
{text:'Configure Accuracy Settings',url:'_docs_Workbench_DG_Configure_Accuracy_Settings.html'},
{text:'Measure Accuracy',url:'_docs_Workbench_DG_Measure_Accuracy.html'}]},
{text:'Deploy and Integrate Performance Criteria into Application',url:'_docs_Workbench_DG_Deploy_and_Integrate_Performance_Criteria_into_Application.html'},
{text:'Advanced Topics in DL Workbench',url:'_docs_Workbench_DG_Restart.html',children:[
{text:'Restart DL Workbench',url:'_docs_Workbench_DG_Restart.html'},
{text:'Enter Docker* Container with DL Workbench',url:'_docs_Workbench_DG_Enter_Docker_Container.html'}]},
{text:'Troubleshooting',url:'_docs_Workbench_DG_Troubleshooting.html'}]},
{text:'Security',url:'_docs_security_guide_introduction.html',children:[
{text:'Introduction',url:'_docs_security_guide_introduction.html'},
{text:'Using Workbench Securely',url:'_docs_security_guide_workbench.html'},
{text:'Using Encrypted Models',url:'_docs_IE_DG_protecting_model_guide.html'}]},
{text:'Optimization Guide',url:'_docs_optimization_guide_dldt_optimization_guide.html'}]},
{text:'OpenVX* Developer Guide',url:'https://software.intel.com/en-us/openvino-ovx-guide'},
{text:'OpenCV* Developer Guide',url:'https://docs.opencv.org/master/'},
{text:'OpenCL™ Developer Guide',url:'https://software.intel.com/en-us/openclsdk-devguide'}]},
{text:'RESOURCES',url:'_docs_resources_introduction.html',children:[
{text:'Resource Overview',url:'_docs_resources_introduction.html'},
{text:'Samples',url:'_docs_IE_DG_Samples_Overview.html',children:[
{text:'Image Classification C++ Sample Async',url:'_inference_engine_samples_classification_sample_async_README.html'},
{text:'Image Classification Python* Sample Async',url:'_inference_engine_ie_bridges_python_sample_classification_sample_async_README.html'},
{text:'Hello Classification C++ Sample',url:'_inference_engine_samples_hello_classification_README.html'},
{text:'Image Classification Python* Sample',url:'_inference_engine_ie_bridges_python_sample_classification_sample_README.html'},
{text:'Hello Reshape SSD C++ Sample',url:'_inference_engine_samples_hello_reshape_ssd_README.html'},
{text:'Hello NV12 Input Classification C++ Sample',url:'_inference_engine_samples_hello_nv12_input_classification_README.html'},
{text:'Hello Query Device C++ Sample',url:'_inference_engine_samples_hello_query_device_README.html'},
{text:'Hello Query Device Python* Sample',url:'_inference_engine_ie_bridges_python_sample_hello_query_device_README.html'},
{text:'Object Detection C++ Sample SSD',url:'_inference_engine_samples_object_detection_sample_ssd_README.html'},
{text:'Object Detection Python* Sample SSD',url:'_inference_engine_ie_bridges_python_sample_object_detection_sample_ssd_README.html'},
{text:'Automatic Speech Recognition C++ Sample',url:'_inference_engine_samples_speech_sample_README.html'},
{text:'Neural Style Transfer C++ Sample',url:'_inference_engine_samples_style_transfer_sample_README.html'},
{text:'Neural Style Transfer Python* Sample',url:'_inference_engine_ie_bridges_python_sample_style_transfer_sample_README.html'},
{text:'Benchmark C++ App',url:'_inference_engine_samples_benchmark_app_README.html'},
{text:'Benchmark Python* App',url:'_inference_engine_tools_benchmark_tool_README.html'}]},
{text:'Demos',url:'_demos_README.html',children:[
{text:'Crossroad Camera Demo',url:'_demos_crossroad_camera_demo_README.html'},
{text:'Interactive Face Detection C++ Demo',url:'_demos_interactive_face_detection_demo_README.html'},
{text:'Interactive Face Recognition Python* Demo',url:'_demos_python_demos_face_recognition_demo_README.html'},
{text:'TensorFlow* Object Detection Mask R-CNNs Segmentation Demo',url:'_demos_mask_rcnn_demo_README.html'},
{text:'Multi-Channel Demo',url:'_demos_multichannel_demo_README.html',children:[
{text:'Multi-Channel Face Detection C++ Demo',url:'_demos_multichannel_demo_fd_README.html'},
{text:'Multi-Channel Human Pose Estimation C++ Demo',url:'_demos_multichannel_demo_hpe_README.html'}]},
{text:'Object Detection Faster R-CNN Demo',url:'_demos_object_detection_demo_faster_rcnn_README.html'},
{text:'Object Detection SSD C++ Demo, Async API Performance Showcase',url:'_demos_object_detection_demo_ssd_async_README.html'},
{text:'Object Detection SSD Python* Demo, Async API Performance Showcase',url:'_demos_python_demos_object_detection_demo_ssd_async_README.html'},
{text:'Security Barrier Camera Demo',url:'_demos_security_barrier_camera_demo_README.html'},
{text:'Image Segmentation C++ Demo',url:'_demos_segmentation_demo_README.html'},
{text:'Image Segmentation Python* Demo',url:'_demos_python_demos_segmentation_demo_README.html'},
{text:'Smart Classroom Demo',url:'_demos_smart_classroom_demo_README.html'},
{text:'Text Detection Demo',url:'_demos_text_detection_demo_README.html'},
{text:'Gaze Estimation Demo',url:'_demos_gaze_estimation_demo_README.html'},
{text:'Human Pose Estimation Demo',url:'_demos_human_pose_estimation_demo_README.html'},
{text:'Pedestrian Tracker Demo',url:'_demos_pedestrian_tracker_demo_README.html'},
{text:'Super Resolution Demo',url:'_demos_super_resolution_demo_README.html'},
{text:'Object Detection YOLO* V3 C++ Demo, Async API Performance Showcase',url:'_demos_object_detection_demo_yolov3_async_README.html'},
{text:'Object Detection YOLO* V3 Python* Demo, Async API Performance Showcase',url:'_demos_python_demos_object_detection_demo_yolov3_async_README.html'},
{text:'Action Recognition Demo',url:'_demos_python_demos_action_recognition_README.html'},
{text:'Instance Segmentation Demo',url:'_demos_python_demos_instance_segmentation_demo_README.html'},
{text:'3D Segmentation Demo',url:'_demos_python_demos_3d_segmentation_demo_README.html'},
{text:'Image Retrieval Python* Demo',url:'_demos_python_demos_image_retrieval_demo_README.html'},
{text:'Multi-Camera Multi-Person Tracking Python* Demo',url:'_demos_python_demos_multi_camera_multi_person_tracking_README.html'}]},
{text:'Tools',url:'_docs_IE_DG_Tools_Overview.html',children:[
{text:'Accuracy Checker Tool',url:'_tools_accuracy_checker_README.html',children:[
{text:'Accuracy Checker Sample',url:'_tools_accuracy_checker_sample_README.html'},
{text:'Configure Caffe* Launcher',url:'_tools_accuracy_checker_accuracy_checker_launcher_caffe_launcher_readme.html'},
{text:'Configure OpenVINO Launcher',url:'_tools_accuracy_checker_accuracy_checker_launcher_dlsdk_launcher_readme.html'},
{text:'Configure OpenCV* Launcher',url:'_tools_accuracy_checker_accuracy_checker_launcher_opencv_launcher_readme.html'},
{text:'Configure MxNet* Launcher',url:'_tools_accuracy_checker_accuracy_checker_launcher_mxnet_launcher_readme.html'},
{text:'Configure TensorFlow* Launcher',url:'_tools_accuracy_checker_accuracy_checker_launcher_tf_launcher_readme.html'},
{text:'Configure TensorFlow* Lite Launcher',url:'_tools_accuracy_checker_accuracy_checker_launcher_tf_lite_launcher_readme.html'},
{text:'Configure ONNX* Runtime Launcher',url:'_tools_accuracy_checker_accuracy_checker_launcher_onnx_runtime_launcher_readme.html'},
{text:'Adapters',url:'_tools_accuracy_checker_accuracy_checker_adapters_README.html'},
{text:'Annotation Converters',url:'_tools_accuracy_checker_accuracy_checker_annotation_converters_README.html'},
{text:'Preprocessors',url:'_tools_accuracy_checker_accuracy_checker_preprocessor_README.html'},
{text:'Postprocessors',url:'_tools_accuracy_checker_accuracy_checker_postprocessor_README.html'},
{text:'Metrics',url:'_tools_accuracy_checker_accuracy_checker_metrics_README.html'},
{text:'Readers',url:'_tools_accuracy_checker_accuracy_checker_data_readers_README.html'}]},
{text:'Calibration Tool',url:'_inference_engine_tools_calibration_tool_README.html'},
{text:'Collect Statistics Tool',url:'_inference_engine_tools_collect_statistics_tool_README.html'},
{text:'Model Downloader',url:'_tools_downloader_README.html'}]},
{text:'Pre-Trained Models (Open Model Zoo)',url:'_models_intel_index.html',children:[
{text:'Object Detection Models',url:'usergroup1.html',children:[
{text:'face-detection-adas-0001',url:'_models_intel_face_detection_adas_0001_description_face_detection_adas_0001.html'},
{text:'face-detection-adas-binary-0001',url:'_models_intel_face_detection_adas_binary_0001_description_face_detection_adas_binary_0001.html'},
{text:'face-detection-retail-0004',url:'_models_intel_face_detection_retail_0004_description_face_detection_retail_0004.html'},
{text:'face-detection-retail-0005',url:'_models_intel_face_detection_retail_0005_description_face_detection_retail_0005.html'},
{text:'person-detection-retail-0002',url:'person-detection-retail-0002.html'},
{text:'person-detection-retail-0013',url:'_models_intel_person_detection_retail_0013_description_person_detection_retail_0013.html'},
{text:'person-detection-action-recognition-0005',url:'_models_intel_person_detection_action_recognition_0005_description_person_detection_action_recognition_0005.html'},
{text:'person-detection-action-recognition-0006',url:'_models_intel_person_detection_action_recognition_0006_description_person_detection_action_recognition_0006.html'},
{text:'person-detection-action-recognition-teacher-0002',url:'_models_intel_person_detection_action_recognition_teacher_0002_description_person_detection_action_recognition_teacher_0002.html'},
{text:'person-detection-raisinghand-recognition-0001',url:'_models_intel_person_detection_raisinghand_recognition_0001_description_person_detection_raisinghand_recognition_0001.html'},
{text:'pedestrian-detection-adas-0002',url:'_models_intel_pedestrian_detection_adas_0002_description_pedestrian_detection_adas_0002.html'},
{text:'pedestrian-detection-adas-binary-0001',url:'_models_intel_pedestrian_detection_adas_binary_0001_description_pedestrian_detection_adas_binary_0001.html'},
{text:'pedestrian-and-vehicle-detector-adas-0001',url:'_models_intel_pedestrian_and_vehicle_detector_adas_0001_description_pedestrian_and_vehicle_detector_adas_0001.html'},
{text:'vehicle-detection-adas-0002',url:'_models_intel_vehicle_detection_adas_0002_description_vehicle_detection_adas_0002.html'},
{text:'vehicle-detection-adas-binary-0001',url:'_models_intel_vehicle_detection_adas_binary_0001_description_vehicle_detection_adas_binary_0001.html'},
{text:'person-vehicle-bike-detection-crossroad-0078',url:'_models_intel_person_vehicle_bike_detection_crossroad_0078_description_person_vehicle_bike_detection_crossroad_0078.html'},
{text:'person-vehicle-bike-detection-crossroad-1016',url:'_models_intel_person_vehicle_bike_detection_crossroad_1016_description_person_vehicle_bike_detection_crossroad_1016.html'},
{text:'vehicle-license-plate-detection-barrier-0106',url:'_models_intel_vehicle_license_plate_detection_barrier_0106_description_vehicle_license_plate_detection_barrier_0106.html'}]},
{text:'Object Recognition Models',url:'usergroup2.html',children:[
{text:'age-gender-recognition-retail-0013',url:'_models_intel_age_gender_recognition_retail_0013_description_age_gender_recognition_retail_0013.html'},
{text:'head-pose-estimation-adas-0001',url:'_models_intel_head_pose_estimation_adas_0001_description_head_pose_estimation_adas_0001.html'},
{text:'license-plate-recognition-barrier-0001',url:'_models_intel_license_plate_recognition_barrier_0001_description_license_plate_recognition_barrier_0001.html'},
{text:'vehicle-attributes-recognition-barrier-0039',url:'_models_intel_vehicle_attributes_recognition_barrier_0039_description_vehicle_attributes_recognition_barrier_0039.html'},
{text:'emotions-recognition-retail-0003',url:'_models_intel_emotions_recognition_retail_0003_description_emotions_recognition_retail_0003.html'},
{text:'landmarks-regression-retail-0009',url:'_models_intel_landmarks_regression_retail_0009_description_landmarks_regression_retail_0009.html'},
{text:'facial-landmarks-35-adas-0002',url:'_models_intel_facial_landmarks_35_adas_0002_description_facial_landmarks_35_adas_0002.html'},
{text:'person-attributes-recognition-crossroad-0230',url:'_models_intel_person_attributes_recognition_crossroad_0230_description_person_attributes_recognition_crossroad_0230.html'},
{text:'gaze-estimation-adas-0002',url:'_models_intel_gaze_estimation_adas_0002_description_gaze_estimation_adas_0002.html'}]},
{text:'Reidentification Models',url:'usergroup3.html',children:[
{text:'person-reidentification-retail-0031',url:'_models_intel_person_reidentification_retail_0031_description_person_reidentification_retail_0031.html'},
{text:'person-reidentification-retail-0079',url:'_models_intel_person_reidentification_retail_0079_description_person_reidentification_retail_0079.html'},
{text:'person-reidentification-retail-0076',url:'_models_intel_person_reidentification_retail_0076_description_person_reidentification_retail_0076.html'},
{text:'face-reidentification-retail-0095',url:'_models_intel_face_reidentification_retail_0095_description_face_reidentification_retail_0095.html'}]},
{text:'Semantic Segmentation Models',url:'usergroup4.html',children:[
{text:'road-segmentation-adas-0001',url:'_models_intel_road_segmentation_adas_0001_description_road_segmentation_adas_0001.html'},
{text:'semantic-segmentation-adas-0001',url:'_models_intel_semantic_segmentation_adas_0001_description_semantic_segmentation_adas_0001.html'}]},
{text:'Instance Segmentation Models',url:'usergroup5.html',children:[
{text:'instance-segmentation-security-0050',url:'_models_intel_instance_segmentation_security_0050_description_instance_segmentation_security_0050.html'},
{text:'instance-segmentation-security-0083',url:'_models_intel_instance_segmentation_security_0083_description_instance_segmentation_security_0083.html'},
{text:'instance-segmentation-security-0010',url:'_models_intel_instance_segmentation_security_0010_description_instance_segmentation_security_0010.html'}]},
{text:'Human Pose Estimation Models',url:'usergroup6.html',children:[
{text:'human-pose-estimation-0001',url:'_models_intel_human_pose_estimation_0001_description_human_pose_estimation_0001.html'}]},
{text:'Image Processing',url:'usergroup7.html',children:[
{text:'single-image-super-resolution-1032',url:'_models_intel_single_image_super_resolution_1032_description_single_image_super_resolution_1032.html'},
{text:'single-image-super-resolution-1033',url:'_models_intel_single_image_super_resolution_1033_description_single_image_super_resolution_1033.html'},
{text:'text-image-super-resolution-0001',url:'_models_intel_text_image_super_resolution_0001_description_text_image_super_resolution_0001.html'}]},
{text:'Text Detection',url:'usergroup8.html',children:[
{text:'text-detection-0003',url:'_models_intel_text_detection_0003_description_text_detection_0003.html'},
{text:'text-detection-0004',url:'_models_intel_text_detection_0004_description_text_detection_0004.html'}]},
{text:'Text Recognition',url:'usergroup9.html',children:[
{text:'text-recognition-0012',url:'_models_intel_text_recognition_0012_description_text_recognition_0012.html'},
{text:'handwritten-score-recognition-0003',url:'_models_intel_handwritten_score_recognition_0003_description_handwritten_score_recognition_0003.html'}]},
{text:'Action Recognition Models',url:'usergroup10.html',children:[
{text:'driver-action-recognition-adas-0002-encoder',url:'_models_intel_driver_action_recognition_adas_0002_encoder_description_driver_action_recognition_adas_0002_encoder.html'},
{text:'driver-action-recognition-adas-0002-decoder',url:'_models_intel_driver_action_recognition_adas_0002_decoder_description_driver_action_recognition_adas_0002_decoder.html'},
{text:'action-recognition-0001-encoder',url:'_models_intel_action_recognition_0001_encoder_description_action_recognition_0001_encoder.html'},
{text:'action-recognition-0001-decoder',url:'_models_intel_action_recognition_0001_decoder_description_action_recognition_0001_decoder.html'}]},
{text:'Image Retrieval',url:'usergroup11.html',children:[
{text:'image-retrieval-0001',url:'_models_intel_image_retrieval_0001_description_image_retrieval_0001.html'}]},
{text:'Compressed Models',url:'usergroup12.html',children:[
{text:'resnet50-binary-0001',url:'_models_intel_resnet50_binary_0001_description_resnet50_binary_0001.html'},
{text:'resnet-50-int8-tf-0001',url:'_models_intel_resnet_50_int8_tf_0001_description_resnet_50_int8_tf_0001.html'},
{text:'resnet-50-int8-sparse-v1-tf-0001',url:'_models_intel_resnet_50_int8_sparse_v1_tf_0001_description_resnet_50_int8_sparse_v1_tf_0001.html'},
{text:'resnet-50-int8-sparse-v2-tf-0001',url:'_models_intel_resnet_50_int8_sparse_v2_tf_0001_description_resnet_50_int8_sparse_v2_tf_0001.html'},
{text:'inceptionv3-int8-tf-0001',url:'_models_intel_inceptionv3_int8_tf_0001_description_inceptionv3_int8_tf_0001.html'},
{text:'inceptionv3-int8-sparse-v1-tf-0001',url:'_models_intel_inceptionv3_int8_sparse_v1_tf_0001_description_inceptionv3_int8_sparse_v1_tf_0001.html'},
{text:'inceptionv3-int8-sparse-v2-tf-0001',url:'_models_intel_inceptionv3_int8_sparse_v2_tf_0001_description_inceptionv3_int8_sparse_v2_tf_0001.html'},
{text:'mobilenetv2-int8-tf-0001',url:'_models_intel_mobilenetv2_int8_tf_0001_description_mobilenetv2_int8_tf_0001.html'},
{text:'mobilenetv2-int8-sparse-v1-tf-0001',url:'_models_intel_mobilenetv2_int8_sparse_v1_tf_0001_description_mobilenetv2_int8_sparse_v1_tf_0001.html'},
{text:'mobilenetv2-int8-sparse-v2-tf-0001',url:'_models_intel_mobilenetv2_int8_sparse_v2_tf_0001_description_mobilenetv2_int8_sparse_v2_tf_0001.html'}]}]}]},
{text:'PERFORMANCE BENCHMARKS',url:'_docs_performance_benchmarks.html',children:[
{text:'Get a Deep Learning Model Performance Boost with Intel® Platforms',url:'_docs_performance_benchmarks.html'}]},
{text:'API REFERENCES',url:'usergroup13.html',children:[
{text:'OpenVX Developer Guide',url:'https://khronos.org/openvx'},
{text:'OpenCV Developer Guide',url:'https://docs.opencv.org/master/'},
{text:'Inference Engine С++ API Reference',url:'annotated.html',children:[
{text:'Data Structures',url:'annotated.html'},
{text:'Class Hierarchy',url:'inherits.html'},
{text:'Namespace Members',url:'namespacemembers.html',children:[
{text:'All',url:'namespacemembers.html',children:[
{text:'a',url:'namespacemembers.html#index_a'},
{text:'b',url:'namespacemembers.html#index_b'},
{text:'c',url:'namespacemembers.html#index_c'},
{text:'d',url:'namespacemembers.html#index_d'},
{text:'f',url:'namespacemembers.html#index_f'},
{text:'g',url:'namespacemembers.html#index_g'},
{text:'h',url:'namespacemembers.html#index_h'},
{text:'i',url:'namespacemembers.html#index_i'},
{text:'k',url:'namespacemembers.html#index_k'},
{text:'l',url:'namespacemembers.html#index_l'},
{text:'m',url:'namespacemembers.html#index_m'},
{text:'n',url:'namespacemembers.html#index_n'},
{text:'o',url:'namespacemembers.html#index_o'},
{text:'r',url:'namespacemembers.html#index_r'},
{text:'s',url:'namespacemembers.html#index_s'},
{text:'t',url:'namespacemembers.html#index_t'},
{text:'y',url:'namespacemembers.html#index_y'}]},
{text:'Functions',url:'namespacemembers_func.html',children:[
{text:'a',url:'namespacemembers_func.html#index_a'},
{text:'c',url:'namespacemembers_func.html#index_c'},
{text:'f',url:'namespacemembers_func.html#index_f'},
{text:'g',url:'namespacemembers_func.html#index_g'},
{text:'m',url:'namespacemembers_func.html#index_m'},
{text:'s',url:'namespacemembers_func.html#index_s'},
{text:'t',url:'namespacemembers_func.html#index_t'}]},
{text:'Variables',url:'namespacemembers_vars.html',children:[
{text:'c',url:'namespacemembers_vars.html#index_c'},
{text:'f',url:'namespacemembers_vars.html#index_f'},
{text:'g',url:'namespacemembers_vars.html#index_g'},
{text:'i',url:'namespacemembers_vars.html#index_i'},
{text:'k',url:'namespacemembers_vars.html#index_k'},
{text:'m',url:'namespacemembers_vars.html#index_m'},
{text:'y',url:'namespacemembers_vars.html#index_y'}]},
{text:'Typedefs',url:'namespacemembers_type.html'},
{text:'Enumerations',url:'namespacemembers_enum.html'},
{text:'Enumerator',url:'namespacemembers_eval.html'}]}]},
{text:'Inference Engine Python API Reference',url:'ie_python_api.html'}]}]}
